local homesick = loadstring(game:HttpGet("https://raw.githubusercontent.com/sharedechoes/Matcha-Luas/refs/heads/main/homesick.lua"))()
homesick.changelogEnabled = false -- enable/disable changelog

local window = homesick.createWindow("homesick example UI", 420, 420)
window:setBadge("dev")

local tab1 = window:addTab("tab1")
local general = tab1:addSection("general", "Left")
general:addToggle("evilbind", "evil bind", false, function(value)
    print("streamproof " .. tostring(value))
end)
general:addToggle("evilbindoff", "evil bind but like off", false, function(value)
    print("evil bind off " .. tostring(value))
end)
general:addToggle("autoRescan", "auto rescan game", true, function(value)
    print("auto rescan " .. tostring(value))
end)
general:addToggle("inputDetect", "input detection", true, function(value)
    print("input detection " .. tostring(value))
end)

local options = tab1:addSection("options", "Right")
options:addCheckbox("watermark", "watermark", true, function(value)
    print("watermark " .. tostring(value))
end)
options:addCheckbox("notifications", "notification sound", false, function(value)
    print("notifications " .. tostring(value))
end)
options:addCheckbox("logNotify", "log notifier", false, function(value)
    print("log notifier " .. tostring(value))
end)

local tab2 = window:addTab("tab2")
local sliders = tab2:addSection("sliders", "Left")
sliders:addSlider("fps", "target fps", 30, 360, 144, function(value)
    print("fps adjusted to " .. tostring(value))
end)
sliders:addSlider("fov", "field of view", 30, 120, 90, function(value)
    print("fov set " .. tostring(value))
end)
sliders:addSlider("raycast", "raycast update (ms)", 100, 5000, 2500, function(value)
    print("raycast ms " .. tostring(value))
end)

local inputs = tab2:addSection("inputs", "Right")
inputs:addInput("username", "username", "", function(value)
    print("username updated to " .. tostring(value))
end)
inputs:addSeparator()
inputs:addDropdown("usage", "usage", {"low", "mid", "high"}, {"mid"}, function(value)
    print("usage level " .. tostring(value[1]))
end)
inputs:addSeparator()
inputs:addMultiDropdown("modes", "active modes", {"stealth", "aggro", "passive", "support"}, {}, function(value)
    print("active modes " .. table.concat(value, " "))
end)
inputs:addSeparator()
inputs:addButton("apply changes", function()
    print("applied changes successfully")
end)

local tab3 = window:addTab("tab3")
local keybinds = tab3:addSection("keybinds", "Left")
keybinds:addToggle("aimbot", "aimbot", false, function(value)
    print("aimbot " .. tostring(value))
end):addKeybind("f", "Toggle", true, function(key, mode)
    print("aimbot keybind changed")
end)
keybinds:addToggle("triggerbot", "triggerbot", false, function(value)
    print("triggerbot " .. tostring(value))
end):addKeybind(nil, "Hold", true)
keybinds:addCheckbox("silent", "silent aim", false, function(value)
    print("silent " .. tostring(value))
end):addKeybind("g", "Toggle", true)

local colors = tab3:addSection("colors", "Right")
colors:addToggle("espHighlight", "esp highlight", true, function(value)
    print("esp highlight " .. tostring(value))
end):addColorpicker("esp color", Color3.fromRGB(222, 196, 151), true, function(color)
    print("esp color updated")
end)
colors:addToggle("teamColor", "team color", false, function(value)
    print("team color " .. tostring(value))
end):addColorpicker("team", Color3.fromRGB(52, 199, 89), true, function(color)
    print("team color updated")
end)
colors:addSeparator()
colors:addText("drag sections around to rearrange")

local evilExample = homesick:CreateBox({
    title = "status",
    showTopbar = true,
    position = Vector2.new(20, 300),
    size = Vector2.new(200, 260),
    visible = true
})
evilExample:SetColor(Color3.fromRGB(30, 27, 25), Color3.fromRGB(222, 196, 151))
evilExample:AddText("header", "homesick demo", Color3.fromRGB(222, 196, 151), 14, nil, "center")
evilExample:AddText("info", "hooray!", Color3.fromRGB(140, 140, 140), 11, nil, "center")
evilExample:AddTimer("bar", 0.75, 1.0, Color3.fromRGB(222, 196, 151))
evilExample:AddButton("btn", "click me", function()
    evilExample:SetText("info", "button clicked", Color3.fromRGB(52, 199, 89))
    evilExample:SetTimer("bar", 0.9, 1.0)
    print("button clicked")
end)
evilExample:AddCheckbox("chk", "enable feature", false, function(val)
    evilExample:SetText("info", val and "feature on" or "feature off", val and Color3.fromRGB(52, 199, 89) or Color3.fromRGB(255, 69, 58))
    print("feature toggled to " .. tostring(val))
end)
evilExample:AddSlider("sld", "speed", 50, 0, 100, 1, function(val)
    evilExample:SetText("info", "speed: " .. tostring(val), Color3.fromRGB(255, 204, 0))
    print("speed is " .. tostring(val))
end)
evilExample:AddSeparator("sep1", "advanced")
evilExample:AddColorpicker("col", "ui accent", Color3.fromRGB(222, 196, 151), function(color)
    evilExample:SetText("info", "color changed", color)
    print("color changed")
end)
evilExample:AddDropdown("drop", "selection", {"option1", "option2", "option3"}, {"option1"}, function(val)
    evilExample:SetText("info", val[1], Color3.fromRGB(222, 196, 151))
    print("dropdown changed to " .. tostring(val[1]))
end)

window.visible = true
window:render()
